version: "3.7"

services:
  nginx:
    image: nginx
    ports:
      - "8000:80"
    environment:
      - NGINX_PORT=80

  redis:
    image: redis
    ports:
      - "6379:6379"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: bash -c "./target/debug/protego"
